//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by API 3_2.rc
//
#define IDC_MYICON                      2
#define MYI_OPENBMP                     101
#define IDD_API3_2_DIALOG               102
#define MYI_SAVEBMP                     103
#define IDS_APP_TITLE                   104
#define IDD_ABOUTBOX                    105
#define IDD_EXITASKBOX                  106
#define IDM_ABOUT                       107
#define IDM_EXIT                        108
#define IDI_API3_2                      109
#define IDI_SMALL                       110
#define IDC_API3_2                      111
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     132
#define IDD_CHOOSEBMP                   133
#define IDD_SETDIMS                     141
#define IDD_ANIM                        142
#define IDD_LISTVIEW                    143
#define IDD_ADDITEM                     144
#define IDD_TRIANGLE                    1000
#define IDD_RECTANGLE                   1001
#define IDD_CIRCLE                      1002
#define IDD_ALLTOGETHER                 1003
#define IDDT_CHOOSEDLGTITLE             1005
#define IDD_SMALLPICT                   1006
#define IDC_ANIMATE                     1007
#define IDC_PICTRECTANGLE               1009
#define IDC_PICTCIRCLE                  1010
#define IDC_PICTALLTOGETHER             1011
#define IDM_CIRCLE                      1012
#define IDS_DRAWCIRCLES                 1012
#define IDC_PICTTRIANGLE                1012
#define IDM_RECT                        1013
#define IDS_DRAWRECTANGLES              1013
#define IDM_TRIANGLE                    1014
#define IDS_DRAWTRIANGLES               1014
#define IDT_MY_TOOLBAR                  1015
#define IDT_MY_STATUSBAR                1016
#define IDB_TOOLBAR_BITMAP              1017
#define IDS_TOOLTIP_CIRCLE              1018
#define IDS_TOOLTIP_RECTANGLE           1019
#define IDS_TOOLTIP_TRIANGLE            1020
#define IDC_API3_2_VIEW                 1021
#define IDB_MY_BMP                      1022
#define IDM_OPEN                        1023
#define IDM_LOAD                        1024
#define IDM_SAVEAS                      1025
#define IDC_RECTWEDIT                   1025
#define MYI_SETDRAWMODE                 1026
#define IDC_RECTWSPIN                   1027
#define MYI_DRAWSTDPICT                 1028
#define IDC_RECTHEDIT                   1029
#define IDB_CIRCLE                      1030
#define IDC_PROGRESS                    1030
#define IDC_RECTHSPIN                   1032
#define IDB_RECTANGLE                   1033
#define IDC_CIRCSLIDER                  1034
#define IDC_LIST                        1034
#define IDB_TRIANGLE                    1035
#define IDB_COMBO                       1036
#define IDS_BRUSH                       1037
#define IDM_BRUSH                       1038
#define MYI_SETCOLOR                    1039
#define IDS_TEXT                        1040
#define IDM_FONT                        1041
#define MYI_SETFONT                     1042
#define IDB_RECTSMALL                   1043
#define IDC_GENRE                       1043
#define IDB_TRISMALL                    1044
#define IDC_RADIOBIG                    1044
#define IDB_CIRCSMALL                   1045
#define IDC_RADIOSMALL                  1045
#define IDB_COMBOSMALL                  1046
#define IDC_RADIOTABLE                  1046
#define IDS_TEXTCLASS                   1047
#define IDS_RECTW                       1048
#define IDS_RECTH                       1049
#define IDS_CIRCLER                     1050
#define IDC_ITEMNAME                    1050
#define IDS_ANIMPATH                    1051
#define IDC_ITEMCREATOR                 1051
#define IDC_ITEMDATE                    1052
#define IDS_AUTOMOBILE                  1052
#define IDS_AUTOMOBILEITEM              1052
#define IDC_ITEMDATESPIN                1053
#define IDS_BOOK                        1053
#define IDS_BOOKITEM                    1053
#define IDC_ITEMTYPE                    1054
#define IDS_FRUIT                       1054
#define IDS_FRUITITEM                   1054
#define IDS_OTHERITEM                   1055
#define IDC_ADDITEM                     1055
#define IDC_REMOVEITEM                  1056
#define IDS_ITEM                        1056
#define IDC_EDITITEM                    1057
#define IDS_ITEMNAME                    1057
#define IDS_ITEMFROM                    1058
#define IDS_ITEMDATE                    1059
#define IDI_CAR                         1060
#define IDI_BOOK                        1061
#define IDI_FRUIT                       1062
#define IDI_OTHER                       1063
#define MYI_CLIPBOARDCOPY               1064
#define MYI_CLIPBOARDPASTE              1065
#define IDM_TEXT                        32777
#define IDM_SETDIMS                     32779
#define IDM_ANIMATION_OPENDEMO          32781
#define IDM_ANIMATION_SEEDEMO           32782
#define IDM_BOOKLIST                    32784
#define ID_FILE_COPY                    32785
#define ID_FILE_PASTE                   32786
#define IDM_COPY                        32787
#define IDM_PASTE                       32788
#define ID_OPTIONS_STEALCOPY            32789
#define IDM_STEALCOPY                   32790
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
