#!/usr/bin/env python

"""
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
"""


import time


def even_valued_fibb_items_sum (s1, s2, limit):
    s = 0
    p1, p2 = s1, s2
    while p2 < limit:
        if p2 % 2 == 0:
            s += p2
        p2, p1 = p1 + p2, p2
    return s


if __name__ == '__main__':
    start = time.time()
    print even_valued_fibb_items_sum(1, 2, 4000000)
    print time.time() - start
